[build]
  base = "frontend"
  publish = "dist"
  command = "npm install && npm run build"

# Single Page App routing: send all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
